### ISSUE TITLE
Add options to remove file/files inside a password protected bucket 

### ISSUE THREAD

**Issue by Neilblaze** [fiatjaf/localfiles#2]
Thanks for building this awesome project. I'm proposing a feature for the same. Since we are storing all of the data on IPFS inside links & binding it with user-specific coordinate(s) & having said that we can also add a scope for protecting those files, can't we add an option of removing a single/multiple files from the same?

**Comment by fiatjaf** [comment]
Sorry, the data is not stored on IṔFS anymore, it's normal old school file storage.

And I can't change the project now because my machine has become unable to compile the source.

I'm (very slowly) working on a v2 of filemap that should be simpler and more reliable.

**Comment by Neilblaze** [comment]
> I'm (very slowly) working on a v2 of filemap that should be simpler and more reliable.

Ahh, I see. Thanks for the update. I'm looking forward to a v2 of it :)
